### ISSUE TITLE
error in execute.py

### ISSUE THREAD

**Issue by Mohanmk1** [Denisolt/Tensorflow_Chat_Bot#1]
Hello Denisolt,

I am facing some error in execute.py, screen shot is attached. could you please help me to fix it.
i am using latest version of tensor flow and python3.6
if you have any other github link for chatbot using tensorflow of later version please share.

![image](https://cloud.githubusercontent.com/assets/28388659/26024020/7b75f0ee-37e6-11e7-91dd-f742c8c038be.png)

**Comment by Denisolt** [comment]
Try creating a virtual environment and downloading specific tensorflow version 0.12. if that doesn't work - let me know. They have changed their library, and now some of the functions don't work properly

**Comment by Mohanmk1** [comment]
hi denisolt,
Normally how long will it take to train 
is it possible to use the excel file to train. if so please let me know the steps.
![image](https://cloud.githubusercontent.com/assets/28388659/26042388/8cc6ec32-3952-11e7-8092-d3c61f46f80e.png)

**Comment by Denisolt** [comment]
So it is actually an infinite loop as far as I know. So it can keep on training and training. My suggestion is to constantly test it, to see how you like the replies.
As example: 
```bash
 global step 91200 learning rate 0.3517 step-time 2.72 perplexity 2.65
   eval: bucket 0 perplexity 361020.83
   eval: bucket 1 perplexity 380485.41
   eval: bucket 2 perplexity 82114.69
   eval: bucket 3 perplexity 51724.13
```
These are the values that I have after training for like a good week on my CPU (2.4 i5)
If you want to increase the speed, check how to use the GPU. 
</br>
It seems like you solved the initial problem, right?
Even though I still haven't tried, but in my opinion it should bepossible to use excel file, however you will probably need to convert it and edit the data, so it is suitable to the needed format.

**Comment by Mohanmk1** [comment]
hi Denisolt,

I thought the issues is solved, but when i tried to run in test mode, i got the below error.
mode= test
![image](https://cloud.githubusercontent.com/assets/28388659/26060357/6cc06a3a-39a2-11e7-92a0-a81b2e9c91eb.png)

mode = serve
![image](https://cloud.githubusercontent.com/assets/28388659/26060422/a7711b8e-39a2-11e7-9d68-a85394208ab7.png)

it would be very helpful can you please support me little bit longer

**Comment by Denisolt** [comment]
So what is the error?

Do not select the serve mode, only test is supported. All you need to do is
open new window of terminal, run virtual environment again, then, open all of the 
.ini files and change train to test on the line: 4
```ini
[strings]

# modes: train, test and serve
mode = test

train_enc = data/train.enc
train_dec = data/train.dec
test_enc = data/test.enc
test_dec = data/test.enc
```
and then run python execute.py again. It should work. let me know specifically what the error is.

**Comment by Denisolt** [comment]
My bad, just loaded the images. Checking rn

**Comment by Denisolt** [comment]
Well, first of all what dataset are you using? 
to test, only use "test mode", serve will not work

**Comment by Mohanmk1** [comment]
i didt use any dataset. i jut executed the program in the train mode, it didt complete fully. in the meantime i just want to executed in test mode. when i did i got the error.

**Comment by Denisolt** [comment]
what do you mean you are not using any dataset? Did you use my repo?
You need sometime for the bot to train, when it trains it encodes the information from dataset,
then when you test, it will decode it. If there is nothing to decode it will give you an error obviously. 
And it seems like that it is the problem. Leave it training for some time, until you see your global step and perplexity values. After that, try testing it.

**Comment by Mohanmk1** [comment]
ok i wll wait till the training is complete , could you please tell me how to use the serve option

**Comment by Denisolt** [comment]
I do not have a lot of knowledge on that, but it seems like it is used in Tensorflow serving:
https://tensorflow.github.io/serving/serving_basic.html </br>
I am not sure tho, I only use the 2 options of train and test
